DROP TABLE IF EXISTS PESSOAS_TAREFAS
DROP TABLE IF EXISTS USUARIOS_TAREFAS
DROP TABLE IF EXISTS PESSOAS
DROP TABLE IF EXISTS TAREFAS
DROP TABLE IF EXISTS USUARIOS
DROP TABLE IF EXISTS AGENDA_MEDICO_HORARIO
DROP TABLE IF EXISTS AGENDA_MEDICO_DIA

DROP TABLE IF EXISTS AGENDA_MEDICO_HORARIO
DROP TABLE IF EXISTS AGENDA_MEDICO_DIA
DROP TABLE IF EXISTS AGENDA_MEDICO 

CREATE TABLE  AGENDA_MEDICO (
	ID INT NOT NULL IDENTITY CONSTRAINT PK_AGENDA_MEDICO_ID PRIMARY KEY,
	MEDICOID INT NOT NULL,
	DATA_CRIACAO DATETIME NOT NULL
);

CREATE TABLE  AGENDA_MEDICO_DIA (
	ID INT NOT NULL IDENTITY CONSTRAINT PK_AGENDA_MEDICO_DIA_ID PRIMARY KEY,	
	DIA VARCHAR(20) NOT NULL,
	DIADISPONIVEL VARCHAR(15) NOT NULL,
	DATA_CRIACAO DATETIME NOT NULL,
	AGENDAMEDICOID INT NOT NULL CONSTRAINT FK_AGENDA_M_DIA_AGENDA_MEDIC FOREIGN KEY REFERENCES AGENDA_MEDICO (ID)
);

CREATE TABLE  AGENDA_MEDICO_HORARIO (
	ID INT NOT NULL IDENTITY CONSTRAINT PK_AGENDA_MEDICO_HORARIO_ID PRIMARY KEY,
	AGENDAMEDICODIAID INT NOT NULL CONSTRAINT FK_AGENDA_M_DIA_AGENDA_MEDIC_HR FOREIGN KEY REFERENCES AGENDA_MEDICO_DIA (ID),
	DATA_CRIACAO DATETIME NOT NULL,
	DATAEHHORA DATETIME NOT NULL,
	DISPONIVEL VARCHAR(15) NOT NULL
);



CREATE TABLE USUARIOS (
	ID INT NOT NULL IDENTITY CONSTRAINT PK_USUARIOS_ID PRIMARY KEY,
	DATA_CRIACAO DATETIME NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	CRM VARCHAR(10) NULL,
	EMAIL VARCHAR(100) NOT NULL,
	SENHA VARCHAR(20) NOT NULL,
	PAPEL VARCHAR(20) NOT NULL
);


CREATE TABLE TAREFAS (
	ID INT NOT NULL IDENTITY CONSTRAINT PK_TAREFAS_ID PRIMARY KEY,
	DATA_CRIACAO DATETIME NOT NULL,
	TITULO VARCHAR(100) NOT NULL,
	DESCRICAO VARCHAR(2000) NOT NULL,
	PRAZO_VALOR INT NOT NULL,
	PRAZO_UNIDADE CHAR(1) NOT NULL, -- M / H / D
	[STATUS] VARCHAR(20) NOT NULL,
	DATA_INICIO DATETIME NULL,
	DATA_FIM DATETIME NULL,
	ID_CRIADOR INT NOT NULL CONSTRAINT FK_TAR_USU_CRIADOR_ID FOREIGN KEY REFERENCES USUARIOS (ID),
	ID_RESPONSAVEL INT NULL CONSTRAINT FK_TAR_USU_RESPONSAVEL_ID FOREIGN KEY REFERENCES USUARIOS (ID)
)

INSERT INTO USUARIOS VALUES (GETDATE(), 'UsuTeste1', 'usuTeste1@email.com.br', 'MTIzNDU2', 'Admin')
INSERT INTO USUARIOS VALUES (GETDATE(), 'UsuTeste2', 'usuTeste2@email.com.br', 'MTIzNDU2', 'Comum')
INSERT INTO USUARIOS VALUES (GETDATE(), 'UsuTeste3', 'usuTeste3@email.com.br', 'MTIzNDU2', 'Comum')

INSERT INTO TAREFAS VALUES (GETDATE(), 'Criar aplicação','Criar aplicação', 4, 'd', 'EmAndamento', '26/04/2024 10:00:00', '30/04/2024 10:00:00', 
(SELECT ID FROM USUARIOS WHERE NOME = 'UsuTeste1'), (SELECT ID FROM USUARIOS WHERE NOME = 'UsuTeste2'))
INSERT INTO TAREFAS VALUES (GETDATE(), 'Refatorar aplicação','Refatorar aplicação', 2, 'h', 'Atribuida', NULL, NULL, 
(SELECT ID FROM USUARIOS WHERE NOME = 'UsuTeste1'), (SELECT ID FROM USUARIOS WHERE NOME = 'UsuTeste3'))
INSERT INTO TAREFAS VALUES (GETDATE(), 'Complitar aplicação','Refatorar aplicação', 30, 'm', 'Pendente', NULL, NULL, 
(SELECT ID FROM USUARIOS WHERE NOME = 'UsuTeste3'), NULL)

SELECT*FROM USUARIOS WITH (NOLOCK)
SELECT*FROM TAREFAS WITH (NOLOCK)

SELECT*FROM TAREFAS T WITH (NOLOCK)
LEFT JOIN USUARIOS U_C WITH (NOLOCK) ON T.ID_CRIADOR = U_C.ID
LEFT JOIN USUARIOS U_R WITH (NOLOCK) ON T.ID_RESPONSAVEL = U_R.ID


INSERT INTO AGENDA_MEDICO VALUES (1,GETDATE());
INSERT INTO AGENDA_MEDICO VALUES (2,GETDATE());
INSERT INTO AGENDA_MEDICO VALUES (3,GETDATE());

INSERT INTO AGENDA_MEDICO_DIA VALUES ('SEGUNDA_FEIRA', 'DISPONIVEL', GETDATE(),1);
INSERT INTO AGENDA_MEDICO_DIA VALUES ('TERÇA_FEIRA', 'DISPONIVEL', GETDATE(),1);
INSERT INTO AGENDA_MEDICO_DIA VALUES ('QUARTA_FEIRA', 'DISPONIVEL', GETDATE(),1);
INSERT INTO AGENDA_MEDICO_DIA VALUES ('QUINTA_FEIRA', 'DISPONIVEL', GETDATE(),1);
INSERT INTO AGENDA_MEDICO_DIA VALUES ('SEXTA_FEIRA', 'DISPONIVEL', GETDATE(),1);
INSERT INTO AGENDA_MEDICO_DIA VALUES ('SABADO', 'INDISPONIVEL', GETDATE(),1);
INSERT INTO AGENDA_MEDICO_DIA VALUES ('DOMINGO', 'INDISPONIVEL', GETDATE(),1);



INSERT INTO AGENDA_MEDICO_HORARIO VALUES(1, GETDATE(), CONVERT(DATETIME ,'2024-07-30 08:00:00.000',102), 'DISPONIVEL');
INSERT INTO AGENDA_MEDICO_HORARIO VALUES(1, GETDATE(), CONVERT(DATETIME , '2024-07-30 08:30:00.000',102), 'DISPONIVEL');
INSERT INTO AGENDA_MEDICO_HORARIO VALUES(1, GETDATE(), CONVERT(DATETIME ,'2024-07-30 09:00:00.000',102), 'DISPONIVEL');
INSERT INTO AGENDA_MEDICO_HORARIO VALUES(1, GETDATE(), CONVERT(DATETIME ,'2024-07-30 09:30:00.000',102), 'DISPONIVEL');
INSERT INTO AGENDA_MEDICO_HORARIO VALUES(1, GETDATE(), CONVERT(DATETIME ,'2024-07-30 10:00:00.000',102), 'DISPONIVEL');

INSERT INTO AGENDA_MEDICO_HORARIO VALUES(2, GETDATE(), CONVERT(DATETIME ,'2024-07-31 08:00:00.000',102), 'DISPONIVEL');
INSERT INTO AGENDA_MEDICO_HORARIO VALUES(2, GETDATE(), CONVERT(DATETIME ,'2024-07-31 08:30:00.000',102), 'DISPONIVEL');
INSERT INTO AGENDA_MEDICO_HORARIO VALUES(2, GETDATE(), CONVERT(DATETIME ,'2024-07-31 09:00:00.000',102), 'DISPONIVEL');
INSERT INTO AGENDA_MEDICO_HORARIO VALUES(2, GETDATE(), CONVERT(DATETIME ,'2024-07-31 09:30:00.000',102), 'DISPONIVEL');
INSERT INTO AGENDA_MEDICO_HORARIO VALUES(2, GETDATE(), CONVERT(DATETIME ,'2024-07-31 10:00:00.000',102), 'DISPONIVEL');

INSERT INTO AGENDA_MEDICO_HORARIO VALUES(3, GETDATE(), CONVERT(DATETIME ,'2024-08-01 08:00:00.000',102), 'DISPONIVEL');
INSERT INTO AGENDA_MEDICO_HORARIO VALUES(3, GETDATE(), CONVERT(DATETIME ,'2024-08-01 08:30:00.000',102), 'DISPONIVEL');
INSERT INTO AGENDA_MEDICO_HORARIO VALUES(3, GETDATE(), CONVERT(DATETIME ,'2024-08-01 09:00:00.000',102), 'DISPONIVEL');
INSERT INTO AGENDA_MEDICO_HORARIO VALUES(3, GETDATE(), CONVERT(DATETIME ,'2024-08-01 09:30:00.000',102), 'DISPONIVEL');
INSERT INTO AGENDA_MEDICO_HORARIO VALUES(3, GETDATE(), CONVERT(DATETIME ,'2024-08-01 10:00:00.000',102), 'DISPONIVEL');

INSERT INTO AGENDA_MEDICO_HORARIO VALUES(4, GETDATE(), CONVERT(DATETIME ,'2024-08-02 08:00:00.000',102), 'DISPONIVEL');
INSERT INTO AGENDA_MEDICO_HORARIO VALUES(4, GETDATE(), CONVERT(DATETIME ,'2024-08-02 08:30:00.000',102), 'DISPONIVEL');
INSERT INTO AGENDA_MEDICO_HORARIO VALUES(4, GETDATE(), CONVERT(DATETIME ,'2024-08-02 09:00:00.000',102), 'DISPONIVEL');
INSERT INTO AGENDA_MEDICO_HORARIO VALUES(4, GETDATE(), CONVERT(DATETIME ,'2024-08-02 09:30:00.000',102), 'DISPONIVEL');
INSERT INTO AGENDA_MEDICO_HORARIO VALUES(4, GETDATE(), CONVERT(DATETIME ,'2024-08-02 10:00:00.000',102), 'DISPONIVEL');

INSERT INTO AGENDA_MEDICO_HORARIO VALUES(5, GETDATE(), CONVERT(DATETIME ,'2024-08-03 08:00:00.000',102), 'DISPONIVEL');
INSERT INTO AGENDA_MEDICO_HORARIO VALUES(5, GETDATE(), CONVERT(DATETIME ,'2024-08-03 08:30:00.000',102), 'DISPONIVEL');
INSERT INTO AGENDA_MEDICO_HORARIO VALUES(5, GETDATE(), CONVERT(DATETIME ,'2024-08-03 09:00:00.000',102), 'DISPONIVEL');
INSERT INTO AGENDA_MEDICO_HORARIO VALUES(5, GETDATE(), CONVERT(DATETIME ,'2024-08-03 09:30:00.000',102), 'DISPONIVEL');
INSERT INTO AGENDA_MEDICO_HORARIO VALUES(5, GETDATE(), CONVERT(DATETIME ,'2024-08-03 10:00:00.000',102), 'DISPONIVEL');

INSERT INTO AGENDA_MEDICO_HORARIO VALUES(6, GETDATE(), CONVERT(DATETIME ,'2024-08-04 08:00:00.000',102), 'DISPONIVEL');
INSERT INTO AGENDA_MEDICO_HORARIO VALUES(6, GETDATE(), CONVERT(DATETIME ,'2024-08-04 08:30:00.000',102), 'DISPONIVEL');
INSERT INTO AGENDA_MEDICO_HORARIO VALUES(6, GETDATE(), CONVERT(DATETIME ,'2024-08-04 09:00:00.000',102), 'DISPONIVEL');
INSERT INTO AGENDA_MEDICO_HORARIO VALUES(6, GETDATE(), CONVERT(DATETIME ,'2024-08-04 09:30:00.000',102), 'DISPONIVEL');
INSERT INTO AGENDA_MEDICO_HORARIO VALUES(6, GETDATE(), CONVERT(DATETIME ,'2024-08-04 10:00:00.000',102), 'DISPONIVEL');


INSERT INTO AGENDA_MEDICO_DIA VALUES ('SEGUNDA_FEIRA', 'DISPONIVEL', GETDATE(),2);
INSERT INTO AGENDA_MEDICO_DIA VALUES ('TERÇA_FEIRA', 'DISPONIVEL', GETDATE(),2);
INSERT INTO AGENDA_MEDICO_DIA VALUES ('QUARTA_FEIRA', 'DISPONIVEL', GETDATE(),2);
INSERT INTO AGENDA_MEDICO_DIA VALUES ('QUINTA_FEIRA', 'DISPONIVEL', GETDATE(),2);
INSERT INTO AGENDA_MEDICO_DIA VALUES ('SEXTA_FEIRA', 'DISPONIVEL', GETDATE(),2);
INSERT INTO AGENDA_MEDICO_DIA VALUES ('SABADO', 'INDISPONIVEL', GETDATE(),2);
INSERT INTO AGENDA_MEDICO_DIA VALUES ('DOMINGO', 'INDISPONIVEL', GETDATE(),2);

INSERT INTO AGENDA_MEDICO_DIA VALUES ('SEGUNDA_FEIRA', 'DISPONIVEL', GETDATE(),3);
INSERT INTO AGENDA_MEDICO_DIA VALUES ('TERÇA_FEIRA', 'DISPONIVEL', GETDATE(),3);
INSERT INTO AGENDA_MEDICO_DIA VALUES ('QUARTA_FEIRA', 'DISPONIVEL', GETDATE(),3);
INSERT INTO AGENDA_MEDICO_DIA VALUES ('QUINTA_FEIRA', 'DISPONIVEL', GETDATE(),3);
INSERT INTO AGENDA_MEDICO_DIA VALUES ('SEXTA_FEIRA', 'DISPONIVEL', GETDATE(),3);
INSERT INTO AGENDA_MEDICO_DIA VALUES ('SABADO', 'INDISPONIVEL', GETDATE(),3);
INSERT INTO AGENDA_MEDICO_DIA VALUES ('DOMINGO', 'INDISPONIVEL', GETDATE(),3);

SELECT 
AM.MEDICOID AS MEDICOID,
AMD.DIA AS DIAAGENDA,
AMD.DIADISPONIVEL AS DISPONIBILIDADEDODIA,
AMH.DATAEHHORA AS HORARIODODIA,
AMH.DISPONIVEL AS DISPONIBILIDADE
FROM AGENDA_MEDICO AM
LEFT JOIN AGENDA_MEDICO_DIA AMD ON AMD.AGENDAMEDICOID = AM.ID
LEFT JOIN AGENDA_MEDICO_HORARIO AMH ON AMH.AGENDAMEDICODIAID = AMD.ID