
DROP TABLE IF EXISTS USUARIOS
DROP TABLE IF EXISTS AGENDA_MEDICO_DIA
DROP TABLE IF EXISTS AGENDA_MEDICO_MES 

CREATE TABLE  AGENDA_MEDICO_MES (
	ID INT NOT NULL IDENTITY CONSTRAINT PK_AGENDA_MEDICO_MES_ID PRIMARY KEY,
	MEDICOID INT NOT NULL,
	MESANO VARCHAR(6) NOT NULL,
	DIA INT NOT NULL,
	DIADISPONIVEL VARCHAR(15) NOT NULL,
	DATA_CRIACAO DATETIME NOT NULL,
	
);
GO

CREATE TABLE AGENDA_MEDICO_DIA (
	ID INT NOT NULL IDENTITY CONSTRAINT PK_AGENDA_MEDICO_DIA_ID PRIMARY KEY,
	HORARIO VARCHAR(5) NOT NULL,
	HORARIODISPONIVEL VARCHAR(15) NOT NULL,
	DATA_CRIACAO DATETIME NOT NULL,
	PACIENTEID INT NULL,
	VERSAOLINHA ROWVERSION,
	AGENDAMEDICOID INT NOT NULL CONSTRAINT FK_AGENDA_M_DIA_AGENDA_MEDIC_MES FOREIGN KEY REFERENCES AGENDA_MEDICO_MES (ID)
);


CREATE TABLE USUARIOS (
	ID INT NOT NULL IDENTITY CONSTRAINT PK_USUARIOS_ID PRIMARY KEY,
	DATA_CRIACAO DATETIME NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	CPF VARCHAR(20) NOT NULL,
	CRM VARCHAR(10) NULL,
	EMAIL VARCHAR(100) NOT NULL,
	SENHA VARCHAR(20) NOT NULL,
	PAPEL VARCHAR(20) NOT NULL
);



INSERT INTO USUARIOS VALUES (GETDATE(), 'MedicoTeste1', '05155418500', '123456','MedicoTeste1@email.com', 'MTIzNDU2', 'Medico')
INSERT INTO USUARIOS VALUES (GETDATE(), 'PacienteTeste1', '03086170530','', 'PacienteTeste1@email.com', 'MTIzNDU2', 'Paciente')



SELECT*FROM USUARIOS WITH (NOLOCK)
